# based on https://github.com/ravendb/ravendb-ruby-client/blob/v4.0/.travis.yml
sudo: required
dist: trusty
language: go

env:
  global:
    - CERTIFICATE=./certs/ruby.pem
    - PASSPHRASE=client11

# TODO: matrix for RAVEN_PROTOCOL
# TODO: rename ruby.pem to sth. else

# TODO: run the server, but we don't need that yet
# TODO: the import rewrite is temporary, only needed for kjk/ravendb-go-client
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libunwind8 wget libicu52 libssl-dev curl unzip gettext libcurl4-openssl-dev zlib1g uuid-dev bzip2 openssl sed
  - mkdir ./certs; cd ./certs
  - openssl genrsa -out ca.key 2048
  - openssl req -new -x509 -key ca.key -out ca.crt -subj "/C=US/ST=Arizona/L=Nevada/O=RavenDB Test CA/OU=RavenDB test CA/CN=localhost/emailAddress=ravendbca@example.com"
  - openssl genrsa -out localhost.key 2048
  - openssl req -new  -key localhost.key -out localhost.csr -subj "/C=US/ST=Arizona/L=Nevada/O=RavenDB Test/OU=RavenDB test/CN=localhost/emailAddress=ravendb@example.com"
  - openssl x509 -req -extensions ext -extfile ../scripts/test_cert.conf -in localhost.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out localhost.crt
  - cat localhost.key localhost.crt > ruby.pem
  - openssl pkcs12 -passout pass:$PASSPHRASE -export -out server.pfx -inkey localhost.key -in localhost.crt
  - sudo cp ca.crt /usr/local/share/ca-certificates/ca.crt
  - sudo update-ca-certificates
  - cd ..
  - wget -O RavenDB.tar.bz2 https://hibernatingrhinos.com/downloads/RavenDB%20for%20Linux%20x64/latest?buildType=nightly
  - tar xvjf RavenDB.tar.bz2
  - rm RavenDB.tar.bz2
  - find . -name "*.go" | xargs sed -i 's/github.com\/ravendb\/ravendb-go-client/github.com\/kjk\/ravendb-go-client/'
  - go get -d -t -v ./...

script:
  - ./travis_run_tests.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
